# Generated by Django 4.1.6 on 2023-02-20 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Wallet name')),
                ('bitcoin', models.CharField(blank=True, max_length=100, verbose_name='Bitcoin Wallet')),
                ('etherium', models.CharField(blank=True, max_length=100, verbose_name='Etherium Wallet')),
                ('usdt', models.CharField(blank=True, max_length=100, verbose_name='USDT Wallet')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=200, verbose_name='Wallet ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('pending', models.BooleanField(default=True, verbose_name='Pending Transactions')),
                ('rejected', models.BooleanField(default=False, verbose_name='Rejected/Canceled Transactions')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users_info')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=200, verbose_name='Wallet ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('pending', models.BooleanField(default=True, verbose_name='Pending Transactions')),
                ('rejected', models.BooleanField(default=False, verbose_name='Rejected/Canceled Transactions')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users_info')),
            ],
        ),
    ]
